### PR TITLE
Fix receiving reminders if users have birthday in the same day

### LINKED ISSUE #59: Users don't receive reminders if they have the same birthday
If user1 and user2 have the same birthday they both won't receive a reminder of each other's birthday.

### PR DESCRIPTION
**Pull request by polina-popova**
Closes #59.

### CODE REVIEW

File: src/birthder.js [hunk 1]
```diff
@@ -208,26 +208,45 @@
         return QUOTES[(Math.random() * QUOTES.length) >> 0];
     }
 
+    /**
+     * Form a reminder message
+     *
+     * @returns {string}
+     */
+     function formReminderMessage(users, targetDay, amountOfTime) {
+        let userNames, userNamesString, toBe, when, message;
```
Comment (eugulixes) [inline src/birthder.js]: Don't inherit a bad style of coding. Instead of this, declare each variable separately. Moreover, it's better to make them constants.

File: src/birthder.js [hunk 2]
```diff
@@ -208,26 +208,45 @@
...
+
+        userNames = users.map(user => user.name);
+        userNamesString = userNames.map(name => `@${name}`).join(', ');
```
Comment (eugulixes) [inline src/birthder.js]: Let's name it `commaSeparatedUsernames`.

File: src/birthder.js [hunk 3]
```diff
@@ -208,26 +208,45 @@
...
 
+    /**
+     * Form a reminder message
+     *
+     * @returns {string}
+     */
+     function formReminderMessage(users, targetDay, amountOfTime) {
+        let userNames, userNamesString, toBe, when, message;
+
+        userNames = users.map(user => user.name);
```
Comment (eugulixes) [inline src/birthder.js]: Let's avoid using Camel Case.

**Review by sibiryoff — DISMISSED** [review]

**Review by eugulixes — APPROVED** [review]
